import Head from 'next/head'
import Image from 'next/image'
import StateAndCityComponent from '../components/StateAndCityComponent'
import ResourceMeasure from '../components/Commons/ResourceMeasure'

//import styles from '../styles/Home.module.css'

function CountryAndCity() {
    const resourceSize = ResourceMeasure();

    return (
        <div className="">
            <Head>
                <title>Tree Shaking Demo | Country-State-City(npm)</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="">
           
                    
                 
                  
                    <div className='flex-wrapper'>
                        <StateAndCityComponent/>
                    </div>
                

            </main>

            
        </div>
    );
}

export default CountryAndCity;