import Head from 'next/head'
import Header from '../components/Header';
import Banner from '../components/HomeBanner';
import BrandLogo from '../components/BrandLogo';
import Arc from '../components/Arc';
import Learning from '../components/LearningPrograme';
import Programme from '../components/ProgramBenefits';
import Growth from '../components/GrowthJourney';
import Testimonials from '../components/Testimonials';
import App from '../components/App';
import Footer from '../components/Footer';
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> 
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" async />
      </Head>
    
    <div>
      <Header/>
      <Banner/>
      <BrandLogo/>
      <Learning/>
      <Programme/>  
      <Arc/>
      <Growth/>
 <Testimonials/>
 <App/>
<Footer/>
    </div>
    </>
  )
}




